GET http://localhost:5000/notes

###
POST http://localhost:5000/add-note
Content-Type: application/json

{
    "title" : "Note 2",
    "content" : "Ini adalah catatan kedua saya"

}

###
PUT http://localhost:5000/edit-note/1
Content-Type: application/json

{
    "title" : "Note 01",
    "content" : "Ini adalah catatan ke satu saya"
}


###
DELETE  http://localhost:5000/delete-note/2

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name" : "admin",
    "email" : "admin@gmail.com",
    "password" : "1234"

}